"use client";

import React from "react";

export function AIDisclaimerChip({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className="chip"
      title="Generated by AI — verify against course materials."
      style={{
        background: "var(--info-soft)",
        color: "var(--info)",
        borderColor: "transparent",
        fontSize: compact ? 9 : 10,
        padding: compact ? "2px 6px" : "3px 8px",
      }}
    >
      <span aria-hidden>◈</span>
      AI
    </span>
  );
}
