"use client";

import React, { useEffect, useState } from "react";
import { useBodyScrollLock } from "@/lib/useBodyScrollLock";

const ACK_KEY = "sapling_disclaimer_ack";

export function DisclaimerModal() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const acked = typeof window !== "undefined" && localStorage.getItem(ACK_KEY) === "true";
    if (!acked) setOpen(true);
  }, []);

  useBodyScrollLock(open);

  const ack = () => {
    localStorage.setItem(ACK_KEY, "true");
    setOpen(false);
  };

  if (!open) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="disclaimer-title"
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.45)",
        zIndex: 220,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 16,
      }}
    >
      <div
        className="card"
        style={{
          maxWidth: 480,
          width: "100%",
          padding: 28,
          boxShadow: "var(--shadow-lg)",
        }}
      >
        <div className="label-micro" style={{ marginBottom: 8 }}>Heads up</div>
        <div id="disclaimer-title" className="h-serif" style={{ fontSize: 22, marginBottom: 10 }}>Sapling uses AI</div>
        <div style={{ fontSize: 13, color: "var(--text-dim)", lineHeight: 1.6, marginBottom: 16 }}>
          Responses are generated by a large language model and can be wrong, incomplete, or inconsistent.
          Use Sapling as a study partner — not a source of truth. Always cross-check important claims against
          your course materials, and never paste sensitive personal information into chat.
        </div>
        <ul style={{ margin: "0 0 18px", padding: "0 0 0 18px", fontSize: 12, color: "var(--text-dim)", lineHeight: 1.7 }}>
          <li>Check citations and facts against primary sources.</li>
          <li>Your conversations may be used to improve the product.</li>
          <li>Don&apos;t share passwords, IDs, or private info.</li>
        </ul>
        <div style={{ display: "flex", justifyContent: "flex-end" }}>
          <button className="btn btn--primary" onClick={ack}>Got it</button>
        </div>
      </div>
    </div>
  );
}
