"""The answer guard's look-alike table (PKG-05 reopen; spec §13 A33).

`learning/_confusables.py` is generated by `scripts/build_confusables.py` from
Unicode's UTS #39 confusables.txt for one pinned Unicode version: every non-ASCII
character that reads as ASCII, mapped to the ASCII text sharing its skeleton,
plus Latin letters with an attachment and Latin small capitals by character name
(UTS #39 lists neither `ɾ` nor most small capitals). The hand-made map it
replaces lacked Cyrillic `г`, IPA `ɾ` and Cherokee `Ꮢ`, and the live grader
credited "г1: yes, г2: yes" in full (red team, round 2).

Pure: no model, no I/O beyond reading the generator's own source."""

from __future__ import annotations

import hashlib
import importlib.util
import unicodedata
from pathlib import Path

import pytest

from learning import _confusables as data

PINNED_UNICODE_VERSION = "15.1.0"
PINNED_SOURCE_SHA256 = "8289f833e4cf78fde56b2080dc0e42934ef5182c9c3f4dd1fbdf2bced69fd5ed"
PINNED_TABLE_SHA256 = "c47e12ee0045fc38e6733d1795bdc6a881fae209ae3bc5a3ca5a6fbff9b95c67"
GENERATOR = Path(__file__).resolve().parents[1] / "scripts" / "build_confusables.py"


def _table_sha256(table: dict[str, str]) -> str:
    lines = "".join(f"{ord(s):04X} {d}\n" for s, d in sorted(table.items()))
    return hashlib.sha256(lines.encode("utf-8")).hexdigest()


def _generator():
    spec = importlib.util.spec_from_file_location("build_confusables", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _reads_as(text: str) -> str:
    """What the guard's detection copy does per character, before case folding:
    NFKD, marks dropped, then the table."""
    base = "".join(
        c for c in unicodedata.normalize("NFKD", text) if unicodedata.category(c) not in {"Mn", "Me"}
    )
    return base.translate(str.maketrans(data.CONFUSABLES))


def test_the_table_is_the_pinned_unicode_data():
    """A regenerated or hand-edited table changes this checksum: regenerate with
    scripts/build_confusables.py and re-pin it, never edit the data module."""
    assert data.UNICODE_VERSION == PINNED_UNICODE_VERSION
    assert data.SOURCE_SHA256 == PINNED_SOURCE_SHA256
    assert _table_sha256(data.CONFUSABLES) == data.TABLE_SHA256 == PINNED_TABLE_SHA256


def test_the_generator_pins_the_same_source():
    gen = _generator()
    assert gen.UNICODE_VERSION == PINNED_UNICODE_VERSION
    assert gen.SOURCE_SHA256 == PINNED_SOURCE_SHA256
    assert PINNED_UNICODE_VERSION in gen.SOURCE_URL


def test_every_entry_maps_a_non_ascii_character_to_ascii():
    """ASCII is never remapped (UTS #39's own skeleton reads `m` as `rn` and `1`
    as `l`, which would break every ASCII rule), and NFKD-decomposable characters
    are left to NFKD, which the guard applies first."""
    assert len(data.CONFUSABLES) > 900
    for source, reading in data.CONFUSABLES.items():
        assert len(source) == 1 and not source.isascii(), source
        assert reading and reading.isascii(), (source, reading)
        assert unicodedata.normalize("NFKD", source) == source, source


@pytest.mark.parametrize(
    "look_alike,reads_as",
    [
        ("г", "r"),  # Cyrillic ghe (red team, round 2)
        ("ɾ", "r"),  # r with fishhook: not in UTS #39, by its character name
        ("Ꮢ", "R"),  # Cherokee sv
        ("а", "a"),  # Cyrillic a, ie, o, er, es
        ("е", "e"),
        ("о", "o"),
        ("р", "p"),
        ("с", "c"),
        ("ο", "o"),  # Greek omicron, nu
        ("ν", "v"),
        ("ʀ", "r"),  # a Latin small capital, by its character name
        ("н", "h"),  # Cyrillic en: UTS #39 reads it as small capital H, then h
        ("ꭱ", "r"),  # Cherokee small e: UTS #39 reads it as small capital R, then r
        ("“", '"'),  # quotes read as the ASCII sharing their skeleton, not as ''
        ("–", "-"),
        ("∶", ":"),
    ],
)
def test_the_table_maps_look_alikes_to_the_ascii_they_read_as(look_alike, reads_as):
    assert data.CONFUSABLES[look_alike] == reads_as


@pytest.mark.parametrize(
    "text,reads_as",
    [
        ("ｒ１：ｙｅｓ", "r1:yes"),  # fullwidth: NFKD
        ("𝐫𝟏 𝒓 𝔯 𝕣 𝗋 𝚛", "r1 r r r r r"),  # mathematical alphanumerics: NFKD
        ("г1: yеs", "r1: yes"),
        ("ЅҮЅТЕМ", "SYSTEM"),
        ("Ꮢ1", "R1"),
    ],
)
def test_nfkd_then_the_table_reads_every_red_team_spelling_as_ascii(text, reads_as):
    assert _reads_as(text) == reads_as


@pytest.mark.parametrize("unmapped", ["—", "м", "к", "λ", "π", "Ω", "Δ", "中"])
def test_characters_without_an_ascii_reading_are_left_alone(unmapped):
    assert unmapped not in data.CONFUSABLES


def test_the_generator_reads_confusables_the_uts39_way():
    """scripts/build_confusables.py on a synthetic excerpt: a skeleton lands on the
    ASCII text that shares it, a name-derived letter closes a gap, and a
    character with no ASCII reading is left out."""
    gen = _generator()
    excerpt = "\n".join(
        [
            "0433 ;\t0072 ;\tMA\t# ( г → r ) CYRILLIC SMALL LETTER GHE → LATIN SMALL LETTER R",
            "201C ;\t0027 0027 ;\tMA\t# ( “ → '' )",
            "0022 ;\t0027 0027 ;\tMA\t# ( \" → '' )",
            "043D ;\t029C ;\tMA\t# ( н → ʜ )",
            "2014 ;\t30FC ;\tMA\t# ( — → ー )",
        ]
    )
    table = gen.build(excerpt)
    assert table["г"] == "r" and table["“"] == '"' and table["н"] == "h" and table["ɾ"] == "r"
    assert "—" not in table and '"' not in table  # no ASCII reading; ASCII never remapped
    assert gen.table_sha256(table) == _table_sha256(table)


def test_the_data_module_renders_back_to_itself():
    """render() of the committed table reproduces the committed module, so the
    file is exactly what the generator writes (no hand edits)."""
    gen = _generator()
    assert gen.render(data.CONFUSABLES) == Path(data.__file__).read_text(encoding="utf-8")
